const E=new TextEncoder();
const json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json","cache-control":"no-store",...h}});
const email=v=>String(v||"").trim().toLowerCase(),name=v=>String(v||"").trim().replace(/\s+/g," ").slice(0,60),rid=(n=32)=>{let a=new Uint8Array(n);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,"0")).join("")},code=()=>{let a=new Uint32Array(1);crypto.getRandomValues(a);return String(a[0]%1e6).padStart(6,"0")};
const b64=a=>btoa(String.fromCharCode(...a)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const unb64=s=>{let x=s.replace(/-/g,"+").replace(/_/g,"/");x+="===".slice((x.length+3)%4);let b=atob(x);return Uint8Array.from(b,c=>c.charCodeAt(0))};
async function sha(t){let d=await crypto.subtle.digest("SHA-256",E.encode(t));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function pb(p,s,it=120000){let k=await crypto.subtle.importKey("raw",E.encode(p),"PBKDF2",false,["deriveBits"]),d=await crypto.subtle.deriveBits({name:"PBKDF2",salt:unb64(s),iterations:it,hash:"SHA-256"},k,256);return b64(new Uint8Array(d))}
async function ph(p,s=rid(16)){return{s,hash:await pb(p,s)}}
function cookie(t,max){return`bdhs_session=${encodeURIComponent(t)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${max}`}
function getCookie(r){let m=(r.headers.get("Cookie")||"").match(/(?:^|;\s*)bdhs_session=([^;]+)/);return m?decodeURIComponent(m[1]):null}
async function user(r,e){let t=getCookie(r);if(!t)return null;return await e.DB.prepare(`SELECT u.id,u.email,u.display_name,u.google_sub FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id_hash=? AND s.expires_at>?`).bind(await sha(t),Date.now()).first()}
async function session(uid,remember,e){let t=rid(32),now=Date.now(),max=remember?2592000:86400;await e.DB.prepare("INSERT INTO sessions(id_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)").bind(await sha(t),uid,now+max*1000,now).run();return{t,max}}
async function mail(e,to,c){if(!e.RESEND_API_KEY)throw Error("RESEND_API_KEY is not configured.");let r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${e.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:e.EMAIL_FROM||"BDHS Schedules <onboarding@resend.dev>",to:[to],subject:"Your BDHS Schedules verification code",text:`BDHS Schedules\n\nYour password reset verification code is:\n\n${c}\n\nThis code expires in 10 minutes.`})});if(!r.ok)throw Error("Email send failed")}
const INIT_SQL=`PRAGMA foreign_keys=ON;CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,password_hash TEXT,password_salt TEXT,google_sub TEXT UNIQUE,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS sessions(id_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at INTEGER NOT NULL,created_at INTEGER NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);CREATE INDEX IF NOT EXISTS idx_sessions_exp ON sessions(expires_at);CREATE TABLE IF NOT EXISTS password_resets(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,code_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,used INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);CREATE INDEX IF NOT EXISTS idx_resets_user ON password_resets(user_id);`;
let initialized=false,initPromise=null;async function ensureDB(e){if(initialized)return;if(!initPromise)initPromise=(async()=>{for(const stmt of INIT_SQL.split(";").map(x=>x.trim()).filter(Boolean)){await e.DB.prepare(stmt).run()}initialized=true})().catch(x=>{initPromise=null;throw x});return initPromise}
async function api(r,e){const origin=r.headers.get("Origin");if(origin&&origin!==new URL(r.url).origin&&origin!==e.APP_ORIGIN)return json({error:"Forbidden origin."},403);await ensureDB(e);let p=new URL(r.url).pathname,b={};if(r.method!=="GET")b=await r.json().catch(()=>({}));
try{
if(r.method==="GET"&&p==="/api/auth/me")return json({authenticated:!!(await user(r,e)),user:await user(r,e)});
if(r.method==="POST"&&p==="/api/auth/signup"){let em=email(b.email),dn=name(b.displayName);if(!em.includes("@")||dn.length<2||typeof b.password!=="string"||b.password.length<10)return json({error:"Enter a valid email, display name, and a password of at least 10 characters."},400);if(await e.DB.prepare("SELECT id FROM users WHERE email=?").bind(em).first())return json({error:"An account with that email already exists."},409);let id=crypto.randomUUID(),h=await ph(b.password),now=Date.now();await e.DB.prepare("INSERT INTO users(id,email,display_name,password_hash,password_salt,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").bind(id,em,dn,h.hash,h.s,now,now).run();let ss=await session(id,!!b.remember,e);return json({ok:true,user:{id,email:em,display_name:dn}},201,{"Set-Cookie":cookie(ss.t,ss.max)})}
if(r.method==="POST"&&p==="/api/auth/login"){let em=email(b.email),u=await e.DB.prepare("SELECT * FROM users WHERE email=?").bind(em).first();if(!u||!u.password_hash)return json({error:"Invalid email or password."},401);if(await pb(b.password,u.password_salt)!==u.password_hash)return json({error:"Invalid email or password."},401);let ss=await session(u.id,!!b.remember,e);return json({ok:true,user:{id:u.id,email:u.email,display_name:u.display_name}},200,{"Set-Cookie":cookie(ss.t,ss.max)})}
if(r.method==="POST"&&p==="/api/auth/logout"){let t=getCookie(r);if(t)await e.DB.prepare("DELETE FROM sessions WHERE id_hash=?").bind(await sha(t)).run();return json({ok:true},200,{"Set-Cookie":"bdhs_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0"})}
if(r.method==="POST"&&p==="/api/auth/forgot"){let em=email(b.email),u=await e.DB.prepare("SELECT id,email FROM users WHERE email=?").bind(em).first(),generic={ok:true,message:"If an account exists for that email, a verification code has been sent."};if(!u)return json(generic);await e.DB.prepare("DELETE FROM password_resets WHERE user_id=?").bind(u.id).run();let c=code(),s=rid(16),now=Date.now();await e.DB.prepare("INSERT INTO password_resets(id,user_id,code_hash,salt,expires_at,attempts,used,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),u.id,await pb(c,s),s,now+600000,0,0,now).run();try{await mail(e,u.email,c)}catch(x){console.error(x);return json({error:"We couldn't send the email. Check the email configuration."},500)}return json(generic)}
if(r.method==="POST"&&p==="/api/auth/verify-reset"){let em=email(b.email),c=String(b.code||"").replace(/\D/g,"").slice(0,6),u=await e.DB.prepare("SELECT id FROM users WHERE email=?").bind(em).first();if(!u||c.length!==6)return json({error:"Invalid or expired verification code."},400);let x=await e.DB.prepare("SELECT * FROM password_resets WHERE user_id=? AND used=0 ORDER BY created_at DESC LIMIT 1").bind(u.id).first();if(!x||x.expires_at<Date.now()||x.attempts>=5)return json({error:"Invalid or expired verification code."},400);if(await pb(c,x.salt)!==x.code_hash){await e.DB.prepare("UPDATE password_resets SET attempts=attempts+1 WHERE id=?").bind(x.id).run();return json({error:"Invalid or expired verification code."},400)}return json({ok:true,resetId:x.id})}
if(r.method==="POST"&&p==="/api/auth/change-password"){if(typeof b.password!=="string"||b.password.length<10)return json({error:"Password must be at least 10 characters."},400);let x=await e.DB.prepare("SELECT * FROM password_resets WHERE id=?").bind(b.resetId).first();if(!x||x.used||x.expires_at<Date.now())return json({error:"This reset request has expired."},400);let h=await ph(b.password);await e.DB.prepare("UPDATE users SET password_hash=?,password_salt=?,updated_at=? WHERE id=?").bind(h.hash,h.s,Date.now(),x.user_id).run();await e.DB.prepare("UPDATE password_resets SET used=1 WHERE id=?").bind(x.id).run();await e.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(x.user_id).run();return json({ok:true})}
if(r.method==="POST"&&p==="/api/auth/google"){if(!e.GOOGLE_CLIENT_ID)return json({error:"Google sign-in is not configured yet."},503);let q=await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${encodeURIComponent(String(b.credential||""))}`);if(!q.ok)return json({error:"Google sign-in could not be verified."},401);let c=await q.json();if(c.aud!==e.GOOGLE_CLIENT_ID||!['https://accounts.google.com','accounts.google.com'].includes(c.iss)||c.email_verified!=="true")return json({error:"Invalid Google sign-in."},401);let em=email(c.email),gs=String(c.sub),u=await e.DB.prepare("SELECT id,email,display_name,google_sub FROM users WHERE google_sub=?").bind(gs).first();if(!u)u=await e.DB.prepare("SELECT id,email,display_name,google_sub FROM users WHERE email=?").bind(em).first();if(u){await e.DB.prepare("UPDATE users SET google_sub=?,updated_at=? WHERE id=?").bind(gs,Date.now(),u.id).run()}else{let id=crypto.randomUUID(),dn=name(c.name||em.split("@")[0]),now=Date.now();await e.DB.prepare("INSERT INTO users(id,email,display_name,google_sub,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(id,em,dn,gs,now,now).run();u={id,email:em,display_name:dn}}let ss=await session(u.id,!!b.remember,e);return json({ok:true,user:{id:u.id,email:u.email,display_name:u.display_name}},200,{"Set-Cookie":cookie(ss.t,ss.max)})}
return json({error:"Not found."},404)}catch(x){console.error(x);return json({error:"Something went wrong on the server."},500)}}
export default{async fetch(r,e){return new URL(r.url).pathname.startsWith("/api/")?api(r,e):e.ASSETS.fetch(r)}};
